### ISSUE TITLE
openmediavault-ldapserver still under dev anywhere

### ISSUE THREAD

**Issue by zzaflemi** [Fats1234/openmediavault-ldapserver#1]
Fats1234, sorry for opening this as an issue, but I'm not sure how else to contact you.  I was curious if you have continued to develop this plugin anywhere?  If not, is the current code mostly working?  I could consider forking the project or even just trying to contributing to it?  I'm looking at openmediavault for a virtual NAS file server for some CIFS file service and this would make it a slam dunk over over Openfiler or RockStor.  

Thanks, you can contact me at afleming@kanren.net

**Comment by Fats1234** [comment]
I have, unfortunately, stopped developing this module for now.  Last I
checked it worked with openmediavault 2.2.14 (which was the version that I
developed it for).  I think it was slightly broken for openmediavault 3,
but it definitely does not work for openmediavault > 4 because of the
changes made for plugins.

Feel free to fork it and modify the code as I don't know when (if ever) I
am going to pick this up again.

Good luck!

**Comment by zzaflemi** [comment]
I really appreciate the response and thanks for the info.  When I have more
time in a few months, I might go ahead and pick it back up.  I'm new to
Openmediavault (but am a long time Linux sysadm) so I might fork it and try
and work on it once I have a better handle on OMV.

Andy

Sincerely,
Andy Fleming
Systems Engineer
[image: KanREN] <http://www.kanren.net/>
[image: phone] 785-856-9820
2029 Becker Drive, Suite 282
Lawrence, Kansas 66047
[image: linkedin]
<https://www.linkedin.com/company/92399?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A92399%2Cidx%3A1-1-1%2CtarId%3A1440002635645%2Ctas%3AKanREN>
 [image: twitter] <https://twitter.com/TheKanREN> [image: twitter]
<http://www.kanren.net/feed/> need support? <support@kanren.net>
